---
name: Deploy New Chart

on:
  workflow_dispatch:
    inputs:
      new_semver:
        description: "New semantic version"
        required: true
      add_tag:
        description: "Create new tag"
        required: true
        type: boolean
        default: true

env:
  HELM_REPO_URL: "https://dmartinol.github.io/rhpam-cop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Package and deploy a new chart version
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Get chart name
        id: chart_name
        run: echo "::set-output name=name::$(cat ./Chart.yaml | grep 'name:' | cut -c 7-)"

      - name: Update chart version
        run: |
          sed -i 's/version: .*/version: ${{ github.event.inputs.new_semver }}/g' ./Chart.yaml
          sed -i 's/appVersion: .*/appVersion: ${{ github.event.inputs.new_semver }}/g' ./Chart.yaml
          sed -i 's/version: .*/version: ${{ github.event.inputs.new_semver }}/g' ./charts/rhpam/Chart.yaml
          sed -i 's/version: .*/version: ${{ github.event.inputs.new_semver }}/g' ./charts/rhsso/Chart.yaml

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v1.1

# Disabled as it fails due to "chart metadata is missing these dependencies: rhpam,rhsso"
# Dependencies must be reviewed and create separate charts for these 2 components
#      - name: Lint chart
#        run: helm lint .

      - name: Package chart
        run: helm package .

      - name: Push new chart file
        run: |
          git add ./Chart.yaml
          git commit -m "build: bumped ${{ steps.chart_name.outputs.name }} to ${{ github.event.inputs.new_semver }} [skip ci]"
          git push
      - name: Push new tag
        if: ${{ github.event.inputs.add_tag }}
        run: |
          git tag "v${{ github.event.inputs.new_semver }}"
          git push origin --tags

      - name: GH-Pages checkout
        run: git checkout gh-pages

      - name: Update repository index
        run: helm repo index --url ${{ env.HELM_REPO_URL }} .

      - name: Deploy new chart
        run: |
          git add ${{ steps.chart_name.outputs.name }}-${{ github.event.inputs.new_semver }}.tgz
          git add index.yaml
          git commit -m "chore: deployed ${{ steps.chart_name.outputs.name }} ${{ github.event.inputs.new_semver }}"
          git push